/**
 * The cross-language contract for identity records.
 *
 * `spec/identity-record-vectors.json` is generated by the Rust
 * implementation. Every vector is rebuilt here from its seed and must match
 * the published record, signed bytes and signature exactly, and every fold
 * case must reach the same live sets — otherwise one side would read the
 * other's published keys as unsigned or retired.
 */
import { webcrypto } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';

import { decodeMultibaseEd25519, importDidKey } from './did-key.js';
import {
  AGENT_KEY_TYPE,
  DEVICE_KEY_TYPE,
  buildAgentRecord,
  buildAgentRetirement,
  buildDeviceRecord,
  buildDeviceRetirement,
  foldAgentRecords,
  foldDeviceRecords,
  recordSignedBytes,
} from './identity-records.js';
import { deriveKid } from './signing.js';

interface Vector {
  name: string;
  seed: string;
  publicKeyMultibase: string;
  kid: string;
  did: string;
  createdAt: string;
  label?: string;
  signedBytes: string;
  bindingSig: string;
  record: Record<string, string>;
}

interface FoldCase {
  name: string;
  at: string;
  deviceRecords: Record<string, string>[];
  agentRecords: Record<string, string>[];
  liveDeviceKids: string[];
  liveAgentDids: string[];
}

const spec = JSON.parse(
  readFileSync(join(__dirname, '../../spec/identity-record-vectors.json'), 'utf8'),
) as { vectors: Vector[]; folds: FoldCase[]; description: string };

beforeAll(() => {
  Object.defineProperty(globalThis, 'crypto', {
    value: webcrypto,
    configurable: true,
    writable: true,
  });
});

function fromHex(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

/** Rebuild a vector from its seed, choosing the shape its record announces. */
async function rebuild(v: Vector): Promise<Record<string, string>> {
  const key = await importDidKey(fromHex(v.seed));
  const r = v.record;
  if (r.$type === DEVICE_KEY_TYPE && r.publicKeyMultibase !== undefined) {
    return buildDeviceRecord(key, v.did, v.createdAt, v.label);
  }
  if (r.$type === DEVICE_KEY_TYPE) {
    return buildDeviceRetirement(key, v.did, r.revokes!, v.createdAt);
  }
  if (r.agentDid !== undefined) {
    return buildAgentRecord(key, v.did, r.agentDid, v.createdAt, v.label);
  }
  return buildAgentRetirement(key, v.did, r.revokes!, v.createdAt);
}

describe('identity record vectors', () => {
  it('has vectors and folds to check (a silently empty contract is no contract)', () => {
    expect(spec.vectors.length).toBe(5);
    expect(spec.folds.length).toBe(7);
    expect(spec.description).toContain(DEVICE_KEY_TYPE);
    expect(spec.description).toContain(AGENT_KEY_TYPE);
  });

  for (const v of spec.vectors) {
    it(`rebuilds ${v.name} from its seed`, async () => {
      const record = await rebuild(v);
      expect(record).toStrictEqual(v.record);
      expect(record.bindingSig).toBe(v.bindingSig);
      // The canonical form of the published record, not of the rebuilt one:
      // this is the string the signature is over on both sides.
      expect(new TextDecoder().decode(recordSignedBytes(v.record))).toBe(v.signedBytes);
    });

    it(`derives the key and kid ${v.name} names`, async () => {
      const key = await importDidKey(fromHex(v.seed));
      expect(key.publicKeyMultibase).toBe(v.publicKeyMultibase);
      expect(await deriveKid(decodeMultibaseEd25519(v.publicKeyMultibase))).toBe(v.kid);
    });
  }

  for (const f of spec.folds) {
    it(`folds ${f.name}`, async () => {
      // Every case in the file is about one account, named by its records.
      const did = f.deviceRecords[0]!.did!;
      const at = new Date(f.at);
      const kids = (await foldDeviceRecords(did, f.deviceRecords, at)).map((k) => k.kid);
      expect(kids).toEqual(f.liveDeviceKids);
      const agents = (await foldAgentRecords(did, f.deviceRecords, f.agentRecords, at)).map(
        (l) => l.agentDid,
      );
      expect(agents).toEqual(f.liveAgentDids);
    });
  }
});
