/**
 * The cross-language contract for encrypted DMs.
 *
 * `spec/e2ee-dm-vectors.json` is generated by the Rust implementation. This
 * one must reproduce every value in it byte-for-byte and read every message
 * in it — a DM one side can write and the other cannot read is not a feature,
 * and nothing but written-down bytes keeps two implementations convergent.
 */
import { webcrypto } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';

import * as ratchet from './ratchet.js';

interface Vectors {
  x3dh: {
    aliceIdentitySecret: string;
    aliceEphemeralSecret: string;
    bobIdentitySecret: string;
    bobSignedPreKeySecret: string;
    bobSpkId: number;
    aliceDid: string;
    sharedSecret: string;
    theirRatchetKey: string;
    initialMessage: { identityKey: string; ephemeralKey: string; spkId: number; did: string };
  };
  kdfRoot: { rootKey: string; dhOutput: string; newRootKey: string; chainKey: string };
  kdfChain: { chainKey: string; messageKey: string; nextChainKey: string };
  header: { ratchetKey: string; prevChainLen: number; msgNum: number; bytes: string };
  session: {
    sharedSecret: string;
    bobSignedPreKeySecret: string;
    bobSignedPreKeyPublic: string;
    aliceRatchetSecret: string;
    aliceInitialState: Record<string, unknown>;
    aliceToBob: Array<{ name: string; nonce: string; plaintext: string; wire: string }>;
    opening: {
      intro: { identityKey: string; ephemeralKey: string; spkId: number; bytes: string };
      nonce: string;
      plaintext: string;
      wire: string;
    };
  };
}

const spec = JSON.parse(
  readFileSync(join(__dirname, '../../spec/e2ee-dm-vectors.json'), 'utf8'),
) as Vectors;

beforeAll(() => {
  Object.defineProperty(globalThis, 'crypto', {
    value: webcrypto,
    configurable: true,
    writable: true,
  });
});

const unhex = (s: string): Uint8Array =>
  Uint8Array.from(s.match(/../g)!.map((b) => parseInt(b, 16)));
const hex = (b: Uint8Array): string => [...b].map((x) => x.toString(16).padStart(2, '0')).join('');

describe('the key derivations', () => {
  it('derives the root and chain keys the vectors publish', async () => {
    const { rootKey, chainKey } = await ratchet.kdfRoot(
      unhex(spec.kdfRoot.rootKey),
      unhex(spec.kdfRoot.dhOutput),
    );
    expect(hex(rootKey)).toBe(spec.kdfRoot.newRootKey);
    expect(hex(chainKey)).toBe(spec.kdfRoot.chainKey);
  });

  it('derives the message key and the next chain key the vectors publish', async () => {
    const { messageKey, nextChainKey } = await ratchet.kdfChain(unhex(spec.kdfChain.chainKey));
    expect(hex(messageKey)).toBe(spec.kdfChain.messageKey);
    expect(hex(nextChainKey)).toBe(spec.kdfChain.nextChainKey);
  });

  it('encodes the header the vectors publish', () => {
    const bytes = ratchet.encodeHeader({
      ratchetKey: unhex(spec.header.ratchetKey),
      prevChainLen: spec.header.prevChainLen,
      msgNum: spec.header.msgNum,
    });
    expect(hex(bytes)).toBe(spec.header.bytes);

    const back = ratchet.decodeHeader(bytes);
    expect(hex(back!.ratchetKey)).toBe(spec.header.ratchetKey);
    expect(back!.prevChainLen).toBe(spec.header.prevChainLen);
    expect(back!.msgNum).toBe(spec.header.msgNum);
  });
});

describe('a session', () => {
  it('starts where the vectors say it starts', async () => {
    const state = await ratchet.initAlice(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeyPublic),
      unhex(spec.session.aliceRatchetSecret),
    );
    const expected = spec.session.aliceInitialState as Record<string, string | number | boolean>;
    expect(hex(state.dhSelfSecret)).toBe(expected.dhSelfSecret);
    expect(hex(state.dhSelfPublic)).toBe(expected.dhSelfPublic);
    expect(hex(state.dhRemote!)).toBe(expected.dhRemote);
    expect(hex(state.rootKey)).toBe(expected.rootKey);
    expect(hex(state.sendChainKey!)).toBe(expected.sendChainKey);
    expect(state.recvChainKey).toBeNull();
    expect(state.sendMsgNum).toBe(0);
    expect(state.isInitiator).toBe(true);
  });

  it('writes the same bytes the Rust initiator wrote', async () => {
    const state = await ratchet.initAlice(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeyPublic),
      unhex(spec.session.aliceRatchetSecret),
    );
    for (const message of spec.session.aliceToBob) {
      const wire = await ratchet.encrypt(state, message.plaintext, unhex(message.nonce));
      expect(wire, `${message.name} must be byte-identical`).toBe(message.wire);
    }
  });

  it('reads what the Rust initiator wrote, from the shared secret and its own pre-key', async () => {
    const state = await ratchet.initBob(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeySecret),
    );
    for (const message of spec.session.aliceToBob) {
      const plaintext = await ratchet.decrypt(state, message.wire);
      expect(plaintext, `${message.name} must decrypt`).toBe(message.plaintext);
    }
  });

  it('talks to itself in both directions, including the responder ratchet step', async () => {
    const alice = await ratchet.initAlice(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeyPublic),
    );
    const bob = await ratchet.initBob(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeySecret),
    );

    const first = await ratchet.encrypt(alice, 'from alice');
    expect(await ratchet.decrypt(bob, first)).toBe('from alice');

    const reply = await ratchet.encrypt(bob, 'from bob');
    expect(await ratchet.decrypt(alice, reply)).toBe('from bob');

    const second = await ratchet.encrypt(alice, 'from alice again');
    expect(await ratchet.decrypt(bob, second)).toBe('from alice again');
  });

  it('opens a conversation with the agreement the responder needs', async () => {
    const opening = spec.session.opening;
    const intro = {
      identityKey: unhex(opening.intro.identityKey),
      ephemeralKey: unhex(opening.intro.ephemeralKey),
      spkId: opening.intro.spkId,
    };
    expect(hex(ratchet.encodeIntro(intro))).toBe(opening.intro.bytes);

    const alice = await ratchet.initAlice(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeyPublic),
      unhex(spec.session.aliceRatchetSecret),
    );
    expect(
      await ratchet.encryptFirst(alice, intro, opening.plaintext, unhex(opening.nonce)),
      'the opening message must be byte-identical',
    ).toBe(opening.wire);

    // A responder reads the agreement before it has any session at all.
    const read = ratchet.introOf(opening.wire);
    expect(read).not.toBeNull();
    expect(hex(read!.ephemeralKey)).toBe(opening.intro.ephemeralKey);
    expect(read!.spkId).toBe(opening.intro.spkId);
    expect(ratchet.introOf(spec.session.aliceToBob[0].wire), 'a later message carries none').toBeNull();

    const bob = await ratchet.initBob(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeySecret),
    );
    expect(await ratchet.decrypt(bob, opening.wire)).toBe(opening.plaintext);
    expect(ratchet.isEncrypted(opening.wire), 'and it reads as encrypted').toBe(true);
  });

  it('keeps messages that arrive out of order', async () => {
    const alice = await ratchet.initAlice(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeyPublic),
    );
    const bob = await ratchet.initBob(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeySecret),
    );

    const one = await ratchet.encrypt(alice, 'one');
    const two = await ratchet.encrypt(alice, 'two');
    const three = await ratchet.encrypt(alice, 'three');

    expect(await ratchet.decrypt(bob, three)).toBe('three');
    expect(await ratchet.decrypt(bob, one)).toBe('one');
    expect(await ratchet.decrypt(bob, two)).toBe('two');
  });

  it('refuses a message a second time', async () => {
    const alice = await ratchet.initAlice(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeyPublic),
    );
    const bob = await ratchet.initBob(
      unhex(spec.session.sharedSecret),
      unhex(spec.session.bobSignedPreKeySecret),
    );
    const wire = await ratchet.encrypt(alice, 'once');
    expect(await ratchet.decrypt(bob, wire)).toBe('once');
    await expect(ratchet.decrypt(bob, wire)).rejects.toThrow();
  });
});
