/**
 * The cross-language contract.
 *
 * `spec/chat-signing-vectors.json` is generated by the Rust implementation.
 * Every other implementation must reproduce each vector's canonical bytes —
 * and its signature — exactly. This test is what stops the two from drifting:
 * a one-byte disagreement about key order, escaping, or where the venue goes
 * would make every signature from one side look like tampering to the other.
 */
import { webcrypto } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';

import * as signing from './signing.js';

interface Vector {
  name: string;
  seed: string;
  publicKey: string;
  kid: string;
  canonical: string;
  sigTag: string;
  input: {
    kind: 'message' | 'delete' | 'react' | 'unreact';
    from: string;
    msgid: string;
    target: string;
    rawTarget?: string;
    dmParticipants?: string[];
    bodyText?: string;
    reply?: string;
    edit?: string;
    subject?: string;
    emoji?: string;
    tags?: Record<string, string>;
  };
}

interface Negative {
  name: string;
  vector: string;
  /** A document-level attack: this canonical against the vector's sigTag. */
  tamperedCanonical?: string;
  /** A tag-level attack: this sigTag against the vector's canonical. */
  sigTag?: string;
  expected: 'invalid' | 'unverifiable';
}

const spec = JSON.parse(
  readFileSync(join(__dirname, '../../spec/chat-signing-vectors.json'), 'utf8'),
) as { vectors: Vector[]; negatives: Negative[] };

beforeAll(() => {
  Object.defineProperty(globalThis, 'crypto', {
    value: webcrypto,
    configurable: true,
    writable: true,
  });
});

/** Rebuild a vector's canonical from its published input, not from its output. */
async function canonicalOf(v: Vector): Promise<string> {
  if (v.input.kind === 'message') {
    return signing.messageCanonical({
      from: v.input.from,
      msgid: v.input.msgid,
      target: v.input.target,
      body: v.input.bodyText!,
      reply: v.input.reply,
      edit: v.input.edit,
      tags: v.input.tags,
    });
  }
  return signing.mutationCanonical({
    kind: v.input.kind,
    from: v.input.from,
    msgid: v.input.msgid,
    target: v.input.target,
    subject: v.input.subject!,
    emoji: v.input.emoji,
  });
}

/** base64url → bytes. */
function fromB64url(s: string): Uint8Array {
  const padded = s + '='.repeat((4 - (s.length % 4)) % 4);
  const bin = atob(padded.replace(/-/g, '+').replace(/_/g, '/'));
  return Uint8Array.from(bin, (c) => c.charCodeAt(0));
}

async function importPublicKey(b64: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('raw', fromB64url(b64) as unknown as ArrayBuffer, 'Ed25519', true, [
    'verify',
  ]);
}

async function verify(canonical: string, sigTag: string, publicKey: string): Promise<boolean> {
  const [alg, , sigB64] = sigTag.split(':');
  if (alg !== 'ed25519') return false;
  return crypto.subtle.verify(
    'Ed25519',
    await importPublicKey(publicKey),
    fromB64url(sigB64!) as unknown as ArrayBuffer,
    new TextEncoder().encode(canonical),
  );
}

describe('chat signing vectors', () => {
  it('has vectors to check (a silently empty contract is no contract)', () => {
    expect(spec.vectors.length).toBeGreaterThan(4);
    expect(spec.negatives.length).toBeGreaterThan(4);
  });

  for (const v of spec.vectors) {
    it(`reproduces the canonical bytes of ${v.name}`, async () => {
      expect(await canonicalOf(v)).toBe(v.canonical);
    });

    it(`verifies the published signature of ${v.name}`, async () => {
      expect(await verify(v.canonical, v.sigTag, v.publicKey)).toBe(true);
    });

    it(`derives the same kid as ${v.name} names`, async () => {
      expect(await signing.deriveKid(fromB64url(v.publicKey))).toBe(v.kid);
      expect(v.sigTag.split(':')[1]).toBe(v.kid);
    });
  }

  /**
   * The three-state verdict, as every verifier must reach it: only a
   * well-formed ed25519 tag whose kid matches the key on hand can be judged
   * `invalid`; a tag we cannot even check — legacy shape, foreign algorithm,
   * a kid naming a key we do not hold — is `unverifiable`, never forgery.
   */
  async function verdict(
    canonical: string,
    sigTag: string,
    publicKey: string,
  ): Promise<'valid' | 'invalid' | 'unverifiable'> {
    const parts = sigTag.split(':');
    if (parts.length !== 3) return 'unverifiable';
    const [alg, kid] = parts;
    if (alg !== 'ed25519') return 'unverifiable';
    if (kid !== (await signing.deriveKid(fromB64url(publicKey)))) return 'unverifiable';
    return (await verify(canonical, sigTag, publicKey)) ? 'valid' : 'invalid';
  }

  for (const n of spec.negatives) {
    it(`reaches "${n.expected}" for ${n.name}`, async () => {
      const v = spec.vectors.find((x) => x.name === n.vector)!;
      expect(v, `negative names unknown vector ${n.vector}`).toBeTruthy();
      // A negative attacks either the document (tamperedCanonical against
      // the vector's real signature) or the tag itself (sigTag against the
      // vector's real canonical) — exactly one of the two is present.
      expect(Boolean(n.tamperedCanonical) !== Boolean(n.sigTag)).toBe(true);
      const canonical = n.tamperedCanonical ?? v.canonical;
      const sigTag = n.sigTag ?? v.sigTag;
      expect(await verdict(canonical, sigTag, v.publicKey)).toBe(n.expected);
    });
  }

  it('folds a channel venue the way the server does', () => {
    const folded = spec.vectors.find((v) => v.input.rawTarget)!;
    expect(signing.channelVenue(folded.input.rawTarget!)).toBe(folded.input.target);
  });

  it('builds a DM venue from the sorted DID pair, from either end', () => {
    const dm = spec.vectors.find((v) => v.input.dmParticipants)!;
    const [a, b] = dm.input.dmParticipants!;
    expect(signing.dmVenue(a!, b!)).toBe(dm.input.target);
    expect(signing.dmVenue(b!, a!)).toBe(dm.input.target);
  });

  it('mints event ids a server will accept: ULID shape, current time', () => {
    const id = signing.newEventId();
    expect(id).toMatch(/^[0-9A-HJKMNP-TV-Z]{26}$/);
    expect(signing.newEventId()).not.toBe(id);
    const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';
    let ms = 0;
    for (const c of id.slice(0, 10)) ms = ms * 32 + CROCKFORD.indexOf(c);
    expect(Math.abs(ms - Date.now())).toBeLessThan(5000);
  });
});
