/**
 * The key agreement, held to the same published bytes as the ratchet above it.
 *
 * `spec/e2ee-dm-vectors.json` is generated by the Rust implementation. If the
 * two sides disagree here they never reach a shared secret at all, and every
 * message after it is unreadable for a reason no user could diagnose.
 */
import { webcrypto } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';

import * as x3dh from './x3dh.js';
import * as ratchet from './ratchet.js';

const spec = JSON.parse(
  readFileSync(join(__dirname, '../../spec/e2ee-dm-vectors.json'), 'utf8'),
) as {
  x3dh: {
    aliceIdentitySecret: string;
    aliceEphemeralSecret: string;
    bobIdentitySecret: string;
    bobSignedPreKeySecret: string;
    bobSpkId: number;
    aliceDid: string;
    sharedSecret: string;
    theirRatchetKey: string;
    initialMessage: { identityKey: string; ephemeralKey: string; spkId: number; did: string };
  };
};

beforeAll(() => {
  Object.defineProperty(globalThis, 'crypto', {
    value: webcrypto,
    configurable: true,
    writable: true,
  });
});

const unhex = (s: string): Uint8Array =>
  Uint8Array.from(s.match(/../g)!.map((b) => parseInt(b, 16)));
const hex = (b: Uint8Array): string => [...b].map((x) => x.toString(16).padStart(2, '0')).join('');

describe('the key agreement', () => {
  it('reaches the secret the vectors publish, from the initiator side', async () => {
    const v = spec.x3dh;
    const result = await x3dh.initiate(
      {
        identitySecret: unhex(v.aliceIdentitySecret),
        did: v.aliceDid,
      },
      {
        identityKey: await pub(v.bobIdentitySecret),
        signedPreKey: await pub(v.bobSignedPreKeySecret),
        spkId: v.bobSpkId,
      },
      unhex(v.aliceEphemeralSecret),
    );

    expect(hex(result.sharedSecret)).toBe(v.sharedSecret);
    expect(hex(result.theirRatchetKey)).toBe(v.theirRatchetKey);
    expect(result.initialMessage).toEqual(v.initialMessage);
  });

  it('reaches the same secret from the responder side', async () => {
    const v = spec.x3dh;
    const shared = await x3dh.respond(
      {
        identitySecret: unhex(v.bobIdentitySecret),
        signedPreKeySecret: unhex(v.bobSignedPreKeySecret),
        spkId: v.bobSpkId,
      },
      v.initialMessage,
    );
    expect(hex(shared)).toBe(v.sharedSecret);
  });

  it('refuses an initial message naming a pre-key we do not hold', async () => {
    const v = spec.x3dh;
    await expect(
      x3dh.respond(
        {
          identitySecret: unhex(v.bobIdentitySecret),
          signedPreKeySecret: unhex(v.bobSignedPreKeySecret),
          spkId: v.bobSpkId,
        },
        { ...v.initialMessage, spkId: v.bobSpkId + 1 },
      ),
    ).rejects.toThrow(/pre-key/i);
  });

  it('carries an agreed secret into a session both sides can talk over', async () => {
    const v = spec.x3dh;
    const initiator = await x3dh.initiate(
      { identitySecret: unhex(v.aliceIdentitySecret), did: v.aliceDid },
      {
        identityKey: await pub(v.bobIdentitySecret),
        signedPreKey: await pub(v.bobSignedPreKeySecret),
        spkId: v.bobSpkId,
      },
    );
    const responderSecret = await x3dh.respond(
      {
        identitySecret: unhex(v.bobIdentitySecret),
        signedPreKeySecret: unhex(v.bobSignedPreKeySecret),
        spkId: v.bobSpkId,
      },
      initiator.initialMessage,
    );

    const alice = await ratchet.initAlice(initiator.sharedSecret, initiator.theirRatchetKey);
    const bob = await ratchet.initBob(responderSecret, unhex(v.bobSignedPreKeySecret));

    const hello = await ratchet.encrypt(alice, 'opened with a real agreement');
    expect(await ratchet.decrypt(bob, hello)).toBe('opened with a real agreement');
    const reply = await ratchet.encrypt(bob, 'and answered');
    expect(await ratchet.decrypt(alice, reply)).toBe('and answered');
  });
});

async function pub(secretHex: string): Promise<Uint8Array> {
  return ratchet.x25519PublicKey(unhex(secretHex));
}
