// Cross-implementation contract tests for act signing.
//
// The vectors in spec/act-signing-vectors.json are generated by the Rust
// implementation (`cargo test -p freeq-sdk generate_signing_vectors --
// --ignored`). This suite must reproduce every canonical, kid, and sigTag
// byte-for-byte — if any assertion here fails after a Rust-side change, the
// two implementations have diverged and signatures made by one will not
// verify on the other.

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { importDidKey } from "@freeq/sdk";
import {
  actCanonical,
  deriveKid,
  publicKeyFromMultibase,
  signActTags,
  verifyActTags,
} from "./act.js";

interface Vector {
  name: string;
  seed: string;
  publicKey: string;
  kid: string;
  tags: Record<string, string>;
  /** The normalized venue — injected by the caller, never read from a tag. */
  target: string;
  /** The event id the signer minted (`+freeq.at/eventid` on the wire). */
  msgid: string;
  canonical: string;
  sigTag: string;
}

/**
 * The named vector's own tags and signature, checked against delivery context
 * its signer never wrote.
 */
interface Negative {
  name: string;
  vector: string;
  expected: "invalid";
  target: string;
  msgid: string;
  tamperedCanonical: string;
}

const fixtures: { vectors: Vector[]; negatives: Negative[] } = JSON.parse(
  readFileSync(
    fileURLToPath(new URL("../../spec/act-signing-vectors.json", import.meta.url)),
    "utf8",
  ),
);

function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

function b64urlDecode(s: string): Uint8Array {
  return new Uint8Array(Buffer.from(s, "base64url"));
}

describe("act signing vectors (shared with Rust)", () => {
  for (const v of fixtures.vectors) {
    describe(v.name, () => {
      it("reproduces the canonical byte-for-byte", () => {
        expect(actCanonical(v.tags, v.target, v.msgid)).toBe(v.canonical);
      });

      it("derives the same kid", async () => {
        expect(await deriveKid(b64urlDecode(v.publicKey))).toBe(v.kid);
      });

      it("verifies the Rust-minted signature", async () => {
        expect(
          await verifyActTags(v.tags, v.target, v.msgid, v.sigTag, b64urlDecode(v.publicKey)),
        ).toEqual({ ok: true });
      });

      it("signs to the identical sigTag from the same seed (deterministic ed25519)", async () => {
        const key = await importDidKey(hexToBytes(v.seed));
        expect(publicKeyFromMultibase(key.publicKeyMultibase)).toEqual(
          b64urlDecode(v.publicKey),
        );
        expect(await signActTags(v.tags, v.target, v.msgid, key)).toBe(v.sigTag);
      });
    });
  }
});

describe("act signing negatives (shared with Rust)", () => {
  it("carries the negatives the fixture file publishes", () => {
    expect(fixtures.negatives.length).toBeGreaterThan(1);
  });

  for (const n of fixtures.negatives) {
    const v = fixtures.vectors.find((x) => x.name === n.vector)!;

    it(`${n.name}: rebuilds the tampered canonical byte-for-byte`, () => {
      expect(v).toBeDefined();
      expect(actCanonical(v.tags, n.target, n.msgid)).toBe(n.tamperedCanonical);
    });

    it(`${n.name}: the vector's own signature reads as ${n.expected}`, async () => {
      expect(
        await verifyActTags(v.tags, n.target, n.msgid, v.sigTag, b64urlDecode(v.publicKey)),
      ).toEqual({ ok: false, reason: "sig-invalid" });
    });
  }
});

describe("verification failures", () => {
  const v = fixtures.vectors[0];
  const pub = () => b64urlDecode(v.publicKey);

  it("altered covered tag → sig-invalid", async () => {
    const tampered = { ...v.tags, "+freeq.at/act-title": "Cite 4 sources on X" };
    expect(await verifyActTags(tampered, v.target, v.msgid, v.sigTag, pub())).toEqual({
      ok: false,
      reason: "sig-invalid",
    });
  });

  it("added act tag → sig-invalid; altered non-covered tag → still valid", async () => {
    const added = { ...v.tags, "+freeq.at/act-priority": "urgent" };
    expect(await verifyActTags(added, v.target, v.msgid, v.sigTag, pub())).toEqual({
      ok: false,
      reason: "sig-invalid",
    });
    // The server's own msgid stamp and the wire copy of the event id: the
    // signed id is the parameter, not either tag.
    const rewritten = {
      ...v.tags,
      msgid: "01JREMINTEDBYPEER00000000",
      "+freeq.at/eventid": "01JREWRITTENBYPEER0000000",
    };
    expect(await verifyActTags(rewritten, v.target, v.msgid, v.sigTag, pub())).toEqual({
      ok: true,
    });
  });

  it("the venue and the event id come from the caller, not from a tag", async () => {
    const spoofed = {
      ...v.tags,
      target: "#random",
      msgid: "01JSPOOFED000000000000000X",
    };
    expect(actCanonical(spoofed, v.target, v.msgid)).toBe(v.canonical);
    expect(await verifyActTags(spoofed, v.target, v.msgid, v.sigTag, pub())).toEqual({
      ok: true,
    });
  });

  it("wrong key → kid-mismatch", async () => {
    const otherPub = b64urlDecode(fixtures.vectors[1].publicKey);
    expect(await verifyActTags(v.tags, v.target, v.msgid, v.sigTag, otherPub)).toEqual({
      ok: false,
      reason: "kid-mismatch",
    });
  });

  it("malformed sig tag / unknown algorithm", async () => {
    expect(
      await verifyActTags(v.tags, v.target, v.msgid, "ed25519:only-one-colon", pub()),
    ).toEqual({ ok: false, reason: "bad-sig-format" });
    expect(await verifyActTags(v.tags, v.target, v.msgid, "rsa:kid:c2ln", pub())).toEqual({
      ok: false,
      reason: "unsupported-algorithm",
    });
  });

  it("wrong-length signature → bad-sig-format (parity with Rust's BadSigFormat)", async () => {
    // Correct kid so the kid check passes; the payload decodes to 3 bytes, not
    // 64. base64url tolerates it silently, so without the length guard this
    // would fall through to a `sig-invalid` — diverging from Rust.
    const kid = v.sigTag.split(":")[1];
    expect(await verifyActTags(v.tags, v.target, v.msgid, `ed25519:${kid}:AAAA`, pub())).toEqual(
      { ok: false, reason: "bad-sig-format" },
    );
  });

  it("no act tags → no-act-tags (and signing returns null)", async () => {
    // Delivery context alone is not a document.
    const none = { msgid: "01J", account: "did:plc:x" };
    expect(await verifyActTags(none, v.target, v.msgid, v.sigTag, pub())).toEqual({
      ok: false,
      reason: "no-act-tags",
    });
    const key = await importDidKey(hexToBytes(v.seed));
    expect(await signActTags(none, v.target, v.msgid, key)).toBeNull();
  });
});
